# Spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
